# Site wide configuration

title: UKULELE TIME
description: "가볍게 우쿨렐레를 즐기는 시간"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://ukuleletime.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Warren Ryu
  email: Warren.Ryu@gmail.com
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: "우쿨렐레 블로거"
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: ukuleletime


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
